### ISSUE TITLE
paper 116 breaks all player messages for me (Chat message validation failed)

### ISSUE THREAD

**Issue by lerokko** [V1nc3ntWasTaken/NoEncryption#5]
### Is there an existing issue for this?

- [X] I have searched the existing issues and have not found a duplicate relating to my issue.

### Are you using the latest version of NoEncryption (Must be using V1nc3ntWasTaken's fork)?

- [X] I am using the latest version of NoEncryption.

### Minecraft Version

1.19.1

### Server Type

- git-paper-116
- NoEncryption v3.1
- Minecraft version 1.19.2!

### Describe the bug

This latest build of paper broke every single player chat message. Paper told me they are not gonna do anything about removing chat signatures for legacy compatibility.

I use chatex (2.8.3) and chatco (0.24 shows ingame as 0.23) as chat plugins

The following messages kick me for "Chat message validation failed"
Regular message

- /w*
- /r*
- /msg* and /minecraft:msg
- message while vanished /with or without trailing /)*
- /me
- /say

*asterisked commands are changed by chat plugins

### Reproducible Test

[Get paper 116 for 1.19.2](https://api.papermc.io/v2/projects/paper/versions/1.19.2/builds/116/downloads/paper-1.19.2-116.jar)
Get NoEncryption (this fork) 3.1
Maybe optional:
[Get chatco](https://dev.bukkit.org/projects/chatco/files/2403680)
[Get chatex](https://www.spigotmc.org/resources/chatex-continued.71041/updates)
Get premiumvanish or [supervanish](https://www.spigotmc.org/resources/supervanish-be-invisible.1331/)
[Get protocollib dev build for premium/supervanish](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/)

### Anything else?

What is MockBukkit? is that a leftover from anohter template?

**Comment by V1nc3ntWasTaken** [comment]
![image_2022-08-08_145433435](https://user-images.githubusercontent.com/79623093/183502910-27437992-b870-4511-91c7-bc7812d3220a.png)
![image_2022-08-08_144738642](https://user-images.githubusercontent.com/79623093/183501834-0d6aad03-d512-4a9f-af9a-16c571139154.png)

Hi! Sorry, but I am unable to re-create your issue environment with the provided information. A few screenshots have been attached with my findings, as well as installed plugins, and server version. Maybe there is some other plugins that could be tampering with chat alongside/instead of ChatCo, and ChatEx?

And thank you for telling me about the typo! I was looking into GitHub issue forms, and MockBukkit was a page I had open that just happened to have issue forms for me to use as a template. (fyi. MockBukkit is a framework for unit testing for the developer end of things)

**Comment by lerokko** [comment]
*2 hours of binary searching and testing later*:

*Mouth foaming.* Yeah its this one.
https://github.com/NEZNAMY/TAB/releases/tag/3.1.4
Who in jeb_s name suspects the tab plugin! Its all working now. Also updated to 4.0. Sorry for wasting your time.

**Comment by V1nc3ntWasTaken** [comment]
It's all okay! Thanks for using NoEncryption
